[website]
name = "MyLabradorPage"

[tracker]
# tracker UDP url with PORT.
url = "udp://localhost:6969"
# tracker REST API url with PORT.
api_url = "http://localhost:1212"
# token needs to be set to use the tracker REST API.
token = "MyAccessToken"
# 12 weeks
token_valid_seconds = 7257600

[net]
port = 3000
#base_url = "https://localhost:3000/api"

[database]
# mode rwc means read/write/create.
# without "c" (create) in "rwc", you'll have to manually create the database.
connect_url = "sqlite://data.db?mode=rwc"
# recommended to keep it at least at 1800 seconds.
# interval should increase with amount of torrents.
torrent_info_update_interval = 3600

[mail]
email_verification_enabled = false
# SMTP server and port
server = ""
port = 25
# username and password for authenticating with the SMTP server
username = ""
password = ""
# email address where mail is sent from
from = "example@email.com"
# email address to which a reply can be sent
reply_to = "noreply@email.com"

[auth]
min_password_length = 6
max_password_length = 64
# IMPORTANT: change to some random chars.
# DO NOT KEEP THIS DEFAULT SECRET.
secret_key = "MaxVerstappenWC2021"

[storage]
# storage path for uploaded torrent files.
upload_path = "./uploads"
